name: deploy site on github page

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-deploy-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: run deploy script
        run: ./deploy.sh
